# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Navee Kaur'
description: 'I am amazing.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
linkedin: navee-kaur
github-user: ''
blog_url: naveekaur.github.io/_pages/blogs.html
email: 'nk33@uw.edu'

# Advanced settings
plugins:
  - jekyll-remote-theme
